# Generated by Django 4.2.7 on 2023-12-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu')),
                ('title', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
